import {profileImage} from "../Profile/assets/index"
const chatsBox = [
    {time : ' 20/20/20',
    lastmsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sender:"Sic Mundus",
    senderImg: {profileImage}},
    {time : ' 20/20/20',
    lastmsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sender:"Sic Mundus",
    senderImg: {profileImage}},
    {time : ' 20/20/20',
    lastmsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sender:"Sic Mundus",
    senderImg: {profileImage}},
    {time : ' 20/20/20',
    lastmsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sender:"Sic Mundus",
    senderImg: {profileImage}},
    {time : ' 20/20/20',
    lastmsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sender:"Sic Mundus",
    senderImg: {profileImage}},
    {time : ' 20/20/20',
    lastmsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sender:"Sic Mundus",
    senderImg: {profileImage}},
    {time : ' 20/20/20',
    lastmsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sender:"Sic Mundus",
    senderImg: {profileImage}},
    {time : ' 20/20/20',
    lastmsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sender:"Sic Mundus",
    senderImg: {profileImage}},
    {time : ' 20/20/20',
    lastmsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sender:"Sic Mundus",
    senderImg: {profileImage}},
    {time : ' 20/20/20',
    lastmsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sender:"Sic Mundus",
    senderImg: {profileImage}},
]

export {chatsBox}