var Notifications = [
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"},
    {action : "#" , 
    notif : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi",
    title:"Sic Mundus Creatus Est",
    date:"20/20/20"}
]

export default Notifications